name: gh-pages deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler-cache: true
    - name: Install ruby dependencies
      run: |
        gem install bundler -v 2.3.13
        bundle install
    - name: Build Jekyll site
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        JEKYLL_ENV=production bundle exec jekyll build
    - name: Deploy Jekyll site
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "reserve.dev@gmail.com"
        export remote_repo="https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        export remote_branch="gh-pages"
        cd _site/
        git init
        git add .
        git commit -m "Rebuild"
        git push --force $remote_repo main:$remote_branch > /dev/null 2>&1
        echo "Done"
